### ISSUE TITLE
Rounded corner have edges borders

### ISSUE THREAD

**Issue by d3ward** [darklinkpower/Stardust#1]
On rounded purple borders for cover in grid view , inner "square" borders are over it

![Immagine 2020-12-25 151107](https://user-images.githubusercontent.com/39910418/103242839-f8cb7d80-4957-11eb-90db-b2b9d30a564d.png)

**Comment by darklinkpower** [comment]
Thanks for the reminder, I had seen the issue before but forgot about it.

At the moment you can set `Grid item Border width` to `0` to not see the square border

![imagen](https://user-images.githubusercontent.com/1389286/103248939-8005fa80-4932-11eb-8625-f8b7e8e3f1a0.png)

**Comment by d3ward** [comment]
This is also fixed  , closing it
