### ISSUE TITLE
[Feature request] Fill width for background video

### ISSUE THREAD

**Issue by Raenock** [darklinkpower/Stardust#11]
Would be great if the newly added video player to the background image on details view could fill the width of the container, like the image does, and clip at the bottom if needed.

Right now, it is being centered with a max height matching the container.

**Comment by darklinkpower** [comment]
Already implemented and can be enabled with those two options (Screenshot is different theme)
![image](https://user-images.githubusercontent.com/1389286/156692401-fb3212db-99ab-43d6-84a7-28d1a6397e2b.png)
