### ISSUE TITLE
[Feature Request] BackgroundChanger support for changing covers in Grid View

### ISSUE THREAD

**Issue by Hydra-Spectre** [darklinkpower/Stardust#12]
I love how there is support for BackgroundChanger changing the backgrounds in Detail View, I wish that the covers are affected as well for both Detail and Grid View.

**Comment by darklinkpower** [comment]
Support for details view was added in https://github.com/darklinkpower/Stardust/commit/8b46ef41d1c496839e3fd6d86cc4abf65c764879

Support for GridView was not added because it caused big performance issues
