### ISSUE TITLE
(Cosmetic) Give the ability to modify distance between top panel and where grid view starts.

### ISSUE THREAD

**Issue by Driesmann** [darklinkpower/Stardust#13]
### Feature Description

As the title suggests, I'd like to see that distance decreased somewhat to give more space to work with in Grid View.

Perhaps the addition of a setting that users themselves can fiddle with to modify that distance to their liking?

In any case, thanks!

### Screenshots

![Untitled](https://user-images.githubusercontent.com/89516301/148922139-1bfc4619-b2cd-445b-b747-6e95534eec30.png)

**Comment by nicksundermeyer** [comment]
I agree with this one, I love everything about this theme but the weird space under the top bar is my one little annoyance with it

**Comment by darklinkpower** [comment]
Done in https://github.com/darklinkpower/Stardust/commit/983fca0ae72671a1d0ca75df13a64ccf6a89511c

**Comment by darklinkpower** [comment]
Just to clarify, the image posted is incorrect since you can see that not all the area is the spacing of the top panel. Some of that area is created by the library group expander

![image](https://user-images.githubusercontent.com/1389286/153964721-db41db95-5a95-4a16-83f4-7b6af63645bd.png)

**Comment by Driesmann** [comment]
Thanks for implementing this nice, albeit small, QOL improvement :)

And yes, my image was incorrect, I was more trying to convey the general gist of my request.
