### ISSUE TITLE
[Feature Request] Option to have rounded corners

### ISSUE THREAD

**Issue by ferrazpedro** [darklinkpower/Stardust#15]
### Feature Description

Hey! Would it be possible to have a ThemeModifier option to give the theme windows rounded corners? Thanks in advance!

**Comment by darklinkpower** [comment]
Aesthetically personally I don't like rounded corners for the theme, although it should be technically possible to add. But what would be the purpose of this? I don't think it is something that adds something to the theme considering it's not something you see when the window is maximized.

**Comment by sirito97** [comment]
It is so easy actually to edit the corners radius of the main window in MainWindowStyle.xaml line 12

**Comment by darklinkpower** [comment]
> It is so easy actually to edit the corners radius of the main window in MainWindowStyle.xaml line 12

It's not that simple. You also need to modify other values to make sure resizing works properly in all the area in the rounded corners and that buttons can be used without issues no matter the sidebar position or if it's disabled

**Comment by sirito97** [comment]
> > It is so easy actually to edit the corners radius of the main window in MainWindowStyle.xaml line 12
> 
> It's not that simple. You also need to modify other values to make sure resizing works properly in all the area in the rounded corners and that buttons can be used without issues no matter the sidebar position or if it's disabled

I really don't remember if I only modified this value because I changed other things too, but it have been a week now and everything working good with rounded corners
`            <Setter.Value>
                <WindowChrome CaptionHeight="25" CornerRadius="17" ResizeBorderThickness="4"
                              NonClientFrameEdges ="None" UseAeroCaptionButtons="False" GlassFrameThickness="0"/>
            </Setter.Value>`

**Comment by darklinkpower** [comment]
Already done some time ago but forgot to close
