### ISSUE TITLE
An Option to Hide the Game Title

### ISSUE THREAD

**Issue by chefreinhold** [darklinkpower/Stardust#16]
### Feature Description

I would love to see an option to hide the game title when viewing the game's detail page. 

Between the **title in box art**, the **logo** (if using the add-on) and in the **side panel**, I find having it written in another font beneath the box-art adds some unnecessary busy-ness to the screen. 

### Screenshots

![Untitled](https://user-images.githubusercontent.com/20997543/154811481-509bd285-2a7a-4d77-9700-3d3cfa15b89e.png)

**Comment by darklinkpower** [comment]
Done as a ThemeModifier extension option to hide game name if logo is being displayed
