### ISSUE TITLE
Ability to have static game name and playtime on grid view (not affected by animations)

### ISSUE THREAD

**Issue by sirito97** [darklinkpower/Stardust#19]
### Feature Description

Is it possible to make game name and playtime on grid view not affected by the zoom hover animations and remain static in place?
I think this will be more consistent as if you look closely when text scale up and down you can notice a change in it.
I will upload a video on that: https://imgur.com/a/4Ir1rAp

It is minimal on lato font but a lot more noticable on other fonts.
### Screenshots

![ULTzEOsoHB](https://user-images.githubusercontent.com/66971290/159675800-6d412ad6-9f93-4331-9f02-29765951c670.png)

**Comment by darklinkpower** [comment]
I'm afraid that I don't know if this is possible. The zoom animation is applied to all the grid view item

![image](https://user-images.githubusercontent.com/1389286/159783807-7339c0aa-694c-41f3-95b3-5d91452251e5.png)

Making it separate, would require making it work to only affect certain parts. There are a lot of elements in the item: Border, game name and its background, cover, name behind cover, etc. and making it only work to only zoom-in the cover and making sure everything works correctly seems a little complicated while also making it an option to only zoom certain parts.

For example, I'm not sure how it would work in the border where the cover and background of the game name connect if only the cover is zoomed in
![image](https://user-images.githubusercontent.com/1389286/159784341-542e11c5-cd09-478f-9ff7-93990c927617.png)

I don't know if this can be and will be implemented but I'll leave the issue open for the moment.
