### ISSUE TITLE
Searchbar Visual Improvements

### ISSUE THREAD

**Issue by sirito97** [darklinkpower/Stardust#21]
### Feature Description

Current searchbar has white border and search icon is shifted to much to the left, it is better to remove that border to match other elements and also better to shift the search icon to the right

### Screenshots

old
![image](https://user-images.githubusercontent.com/66971290/160654182-ee6ec6be-18f8-4a4e-90ff-2cc691453315.png)
new
![unknown](https://user-images.githubusercontent.com/66971290/160654338-f6e21f4d-4312-4d2a-b68d-ca90f8f1b930.png)

**Comment by darklinkpower** [comment]
Done
