### ISSUE TITLE
Add thememodifier setting to disable cover image in Details view

### ISSUE THREAD

**Issue by poetickatana** [darklinkpower/Stardust#23]
### Feature Description

I personally prefer to use left-aligned logos instead of covers in the Details view. It would be nice to have a Thememodifier option to hide game covers in that view. I'm not sure if this fits with the general motif that you're going for in this theme, but I see no harm in adding the option and having it disabled by default.

**Comment by darklinkpower** [comment]
I'm not understanding, is what you are requesting different from disabling the cover in settings?

About the logo, the position is handled in the Extra Metadata Loader extension settings.

**Comment by poetickatana** [comment]
Never mind. The theme that I normally use has its own option to toggle covers/banners in Details view. I forgot that covers can also be toggled from Playnite's options menu. Disregard this request.
