### ISSUE TITLE
Set minimum height for logo/cover image region grid

### ISSUE THREAD

**Issue by poetickatana** [darklinkpower/Stardust#24]
### Feature Description

The height of the row 1 grid that contains the logo/cover image in the Details view is set to Auto. This is fine typically, but If covers visibility is disabled and logos are used instead, the height of this row will vary from game to game because logo heights are very inconsistent. This causes the grids below row 1 to shift vertically when switching between games. I was able to eliminate this effect by setting a MinHeight parameter for row 1 with a value that's larger than the height of most of my logos. In my case, a value of "200" did the trick.

Can this be incorporated into the theme, either as a hard-coded value or as a setting?

```
<Grid.RowDefinitions>
    <RowDefinition Height="{Settings CalculatedGameDetailsIndentation}" MinHeight="{DynamicResource PanelTopPanelSeparatorHeight}" />
    <RowDefinition Height="Auto" />  <-- Variable height. I added MinHeight="200"
    <RowDefinition Height="Auto" />
    <RowDefinition Height="Auto" />
    <RowDefinition Height="*" />
</Grid.RowDefinitions>
```

**Comment by poetickatana** [comment]
An alternate solution, I suppose, would be to add a "Minimum height of logos" setting under Extra Metadata Loader -> Logo settings.

**Comment by darklinkpower** [comment]
Fixed in https://github.com/darklinkpower/Stardust/commit/e3603bc4d47404efec03f04f639ac17fbc113082
