### ISSUE TITLE
Add visual indicator of game state on Grid View

### ISSUE THREAD

**Issue by Dorennor** [darklinkpower/Stardust#26]
### Feature Description

It would be great if the purple highlight around the selected game (the one that appears after clicking the LMB) was automatically put on the game when you click the "play" or "info" button. Purely from an aesthetic point of view, it seems somehow logical to me.

**Comment by darklinkpower** [comment]
Hello, I'm having trouble understanding what element specifically you are referring to. In what view is this? what do you mean by "LMB"? If possible, please share a screenshot of the element you are referring to

**Comment by Dorennor** [comment]
It was about violet border around active (choosen) element with LBM.
![image](https://user-images.githubusercontent.com/40647609/166163266-7aef7167-ebc3-47b3-9a0e-bea7a9c07c4d.png)
For example I will press LBM on game and this game will highlight with violet border. But if i will press LBM on button "Play" of button "I"(or "Info") it doesn't move to game that I've runed.

**Comment by darklinkpower** [comment]
If I understand right, I think by "LBM" you instead mean "LMB" which means `Left Mouse Button` right? This is a selection border but pressing the Play Button doesn't select the game. Adding this border could cause UX issues, as the game could be mistaken as being selected when it actually has not been selected. Perhaps another idea is to add a different visual indicator to games that are running or in other state, similar to how it's done on details view.

**Comment by Dorennor** [comment]
> If I understand right, I think by "LBM" you instead mean "LMB" which means `Left Mouse Button` right? This is a selection border but pressing the Play Button doesn't select the game. Adding this border could cause UX issues, as the game could be mistaken as being selected when it actually has not been selected. Perhaps another idea is to add a different visual indicator to games that are running or in other state, similar to how it's done on details view.

Yes, sorry for my mistake about "LMB". Your idea generally reflects my suggestion: to create an indicator of a running game.

**Comment by darklinkpower** [comment]
Done in https://github.com/darklinkpower/Stardust/commit/9f07eb54b41aff04377f9b93418200abca7fbc8c
