### ISSUE TITLE
Option for sharp edges for game covers

### ISSUE THREAD

**Issue by Hydra-Spectre** [darklinkpower/Stardust#27]
### Feature Description

I have always been a bit tipped off with the rounded cover corners seeing as how they crop a bit of the cover images.
I really hope that ThemeManager would allow the darklinkpower themes for the covers to either have rounded corners of sharp corners.

This would be great.

**Comment by darklinkpower** [comment]
Done in https://github.com/darklinkpower/Stardust/commit/a857565f30a4a0cd8e5b1229d9869293048363d6
