### ISSUE TITLE
Add a ThemeModifier settings slider to control the darkness of the background cover art in Details View (Similar to the Mythic theme)

### ISSUE THREAD

**Issue by poetickatana** [darklinkpower/Stardust#31]
### Feature Description

Suggestion to add a ThemeModifier setting to control the opacity of the dark layer covering the background image in Details View.

Such a setting already exists in the Mythic theme.

### Screenshots

![image](https://user-images.githubusercontent.com/95546621/197644081-30faf6fa-c297-42e5-905b-da53f0e35b78.png)

**Comment by darklinkpower** [comment]
Done
