### ISSUE TITLE
Game information in 'details' view starts too low down

### ISSUE THREAD

**Issue by Bzly** [darklinkpower/Stardust#33]
In the screenshots in this repo the game portrait icon, name and details all start at the top of the details pane (after some small padding for aesthetic reasons, of course). 

For me, they start a good few hundred pixels lower:
![image](https://user-images.githubusercontent.com/6991971/210387758-a92bf8ae-ac4a-4cbe-a178-175f5ae16685.png)

Is this intentional behaviour that hasn't been reflected in screenshots, a setting that is different to those on display in the screenshots (I would assume everything's default, though), or a bug?

If you're calculating anything based on monitor aspect ratio, my primary is an ultrawide - which has led to strange issues like this in the past.

**Comment by darklinkpower** [comment]
The distance is controlled by this setting

![image](https://user-images.githubusercontent.com/1389286/210390669-4bf5bc38-71ae-4553-8f72-37e654ff1dac.png)

**Comment by darklinkpower** [comment]
Closing, let me know if you still have an issue.

**Comment by Bzly** [comment]
Thanks for pointing that out; it's much nicer. Should the screenshots of the skin not match the default appearance?

I think it would be good if either the screenshots were updated to accurately represent the default look of the theme, or preferably the default value updated to match the screenshots.
