### ISSUE TITLE
Option to display Completion Status in place of Time Played on Grid View

### ISSUE THREAD

**Issue by subhive** [darklinkpower/Stardust#34]
### Feature Description

Would it be possible please to add the option to display the "Completion Status" in place of the "Time Played" status under the game title on the Grid View.

To optionally take it one step further; Not sure if there are other options that could be swapped out here, if it's possible to select (one or multiple) what's displayed from a list - e.g. Time Played, Completion Status, Star Rating, Library, Platform, Genre, Developer, Series, etc.

**Comment by darklinkpower** [comment]
Done in https://github.com/darklinkpower/Stardust/commit/b741ebe9b6b17e7462f2a54ed0cdc9fafd6d090e

Making it configurable to show any field is not possible due to theme-ing limitations. Making it fully configurable requires for this to be implemented as a native Playnite functionality.
