### ISSUE TITLE
Multi-platform icons missing after update

### ISSUE THREAD

**Issue by profucius** [darklinkpower/Stardust#39]
### Bug Description

I think this is a bug, not fully sure after reading the changelog. After updating to v2.55, I can no longer see any of the platform icons in grid view (at the top-right of box art). Before the update, they would only show if a game was considered a duplicate by DuplicateHider, and clicking on the icons would change which game was selected in the sidebar.

I've tried digging through the settings of both Stardust, and DuplicateHider, and cannot find a setting to turn this back on.

If I have simply overlooked a setting to re-enable this, please advise.

**Comment by profucius** [comment]
I've noticed that this isn't a bug per se, it appears you've moved the multi-platform icons from the box art over to the sidebar. While I think having the choices on the sidebar is a good idea, I request that you please add an option to the addon to put the icons back onto the box art again. 

I heavily depended on using these icons to see my multi-platform games at a glance. Without these box art icons, now I have to manually click each game and look over to the sidebar to see if it is multi-platform or not. Please, please add this back!

**Comment by JPDelprat** [comment]
Same request for me. It was very useful to see platforms at a glance in grid view.

**Comment by darklinkpower** [comment]
I removed them from all my themes in updates some time ago but I added them in the game details panel, next to the game name. The main reason is that their presence was causing a ***very*** heavy performance hit, which was most noticeable when scrolling. This hit happened as long as the extension was enabled and disabling the control in the extension settings didn't improve performance.

In fact, it was the single element with the most processing time required, more so than everything else combined in the grid item itself.

![image](https://github.com/darklinkpower/Stardust/assets/1389286/cc418731-79f4-44ea-a845-24d2dd2afb2e)

The grid game element took 5.68ms to process and of that, the Duplicate Hider control/icons took 4.02ms of that, representing 70% of the total, which is too much.

I don't know what's causing it but I could maybe add it back if the performance hit gets resolved, I hope you can understand.

**Comment by profucius** [comment]
Thanks for the detailed reply @darklinkpower, that helps to understand the reasoning.

I wonder if it would be possible for you to split the difference and add it back as an option to the settings panel (default disabled, and with a performance warning) for those of us with beefy PCs and/or who don't mind the performance difference.

I actually don't really notice performance difference without the feature on my PC. Maybe it's subjective, but personally I would prefer the feature over some percentage of performance, of which I was already satisfied enough with prior to the removal.

Then once the root cause is perhaps discovered, it could be easy to make some changes to it already being re-included.

If it's not too much trouble to do. I do really want this feature back even 2 months later. I play on a 55" 4k screen, and so screen elements are far enough apart that it can be troublesome and fatiguing to look back and forth between the game name area on each game just to see if a duplicate on another platform exists (of which I have many). Thanks for your consideration.

**Comment by darklinkpower** [comment]
@profucius unfortunately not possible as its presence causes the performance hit, whether its disabled, enabled, visible, invisible, etc. There's no way to have it there without causing this issue.

> I actually don't really notice performance difference without the feature on my PC. Maybe it's subjective

It could be that the hit can range from non-existent to heavy like in my case depending on the PC, although not exactly subjective since profiling tests I made and that I included in my previous comments shows an accurate representation of the issue.

I'm really sorry for removing this, it was not a decision I took lightly because I knew there would be people that would not like this change but I've spent a lot of time improving performance and this was pretty much the only way to improve in this aspect.

If you don't mind missing a few updates, you can install the last version with this feature here, updates after this one are not essential so you wouldn't be missing anything important: https://github.com/darklinkpower/Stardust/releases/download/2.54/Stardust_2.0_1fb333b2-255b-43dd-aec1-8e2f2d5ea002_2_54.pthm

**Comment by profucius** [comment]
I appreciate you explaining it to me, and that helps me understand. I do like staying on the latest version with new features, so I'll stick with it.

I wonder if there is any other way to indicate that a game is a duplicate, even if not indicating which platforms it is a duplicate of. Do you think this is possible with perhaps a little icon or colored edge/tag, etc on or around the box art? Or is it in your findings that putting anything on the box art causes the performance hit?

**Comment by darklinkpower** [comment]
> I wonder if there is any other way to indicate that a game is a duplicate, even if not indicating which platforms it is a duplicate of. Do you think this is possible with perhaps a little icon or colored edge/tag, etc on or around the box art?

That's not possible, themes have no way to know if a game has a duplicate game by themselves, it needs to be done via Playnite (which doesn't have this feature) or extension like DuplicateHider (Which causes this issue)

**Comment by JPDelprat** [comment]
Thank you very much, Darklinpower, for your explanation. Performance optimization is a very good reason for this change.

In my case, however, I would appreciate it if you could add an option to restore the platform indication in the grid view, perhaps with a performance warning (I don't know if it's possible to add options to themes).

Perhaps you could ask DuplicateHider to provide a more efficient way of getting the information you need.

Anyway, don't worry: for the time being, I've switched to another theme that still offers this possibility. Although I preferred your theme, it's sufficient for my needs.

Thanks again for your help

Translated with www.DeepL.com/Translator (free version)

**Comment by darklinkpower** [comment]
> In my case, however, I would appreciate it if you could add an option to restore the platform indication in the grid view, perhaps with a performance warning (I don't know if it's possible to add options to themes).

Hi, as I've explained in a prior comment an option for it is not possible https://github.com/darklinkpower/Stardust/issues/39#issuecomment-1763185607

In the same comment you can also find the last release with support for it if you want.

**Comment by JPDelprat** [comment]
> Hi, as I've explained in a prior comment an option for it is not possible [#39 (comment)](https://github.com/darklinkpower/Stardust/issues/39#issuecomment-1763185607)

Sorry, I didn't see this point in your answers.

**Comment by profucius** [comment]
I'll close this issue since it isn't possible to reimplement at the time. If there is ever an opportunity to include some type of indicator on the box art itself without major performance issues, please consider implementing that at a future date. Thank you
