### ISSUE TITLE
Gap between edge of window and sidebar in grid view since update

### ISSUE THREAD

**Issue by Ryziel** [darklinkpower/Stardust#43]
### Bug Description

Why is there now a gap on the left between the sidebar and the edge of the window in grid view? It looks terrible and was not there before the recent update.

### Screenshots

![stardust](https://github.com/darklinkpower/Stardust/assets/140835001/a5c1cc65-f3f1-4fff-ab8f-5055fec7a1a7)

**Comment by darklinkpower** [comment]
It was unintended, fixed in https://github.com/darklinkpower/Stardust/commit/a6fd5acfde910c93a590bdeaf1e8288f6b142c1b
