### ISSUE TITLE
[BUG] Grainy Background Image

### ISSUE THREAD

**Issue by Official-Husko** [darklinkpower/Stardust#44]
### Bug Description

There seems to be a bug introduced in the latest release 2.61 which makes the background images grainy.

### To Reproduce

Install version 2.61 and look at the background

### **Background in 2.60**
![version_2-60](https://github.com/darklinkpower/Stardust/assets/27901510/9f781863-dd8f-4bb0-902c-e90dd306832a)

### **Background in 2.61**
![version_2-61](https://github.com/darklinkpower/Stardust/assets/27901510/fdaa6b32-23d0-4f1d-93b7-f337e249d119)

**Comment by darklinkpower** [comment]
It's a noise layer to improve readability of foreground elements. I'll reduce it and implement an option to control it in a future update, for the moment you can modify this value in your local installation: https://github.com/darklinkpower/Stardust/blob/2b0892d6c6350a6d2b5dcedb90db4b68d9cf4206/source/Constants.xaml#L27

**Comment by Official-Husko** [comment]
> It's a noise layer to improve readability of foreground elements. I'll reduce it and implement an option to control it in a future update, for the moment you can modify this value in your local installation:
> 
> https://github.com/darklinkpower/Stardust/blob/2b0892d6c6350a6d2b5dcedb90db4b68d9cf4206/source/Constants.xaml#L27

Thank you for the info and for the theme of course. I really enjoy it :D

**Comment by darklinkpower** [comment]
Glad you like it!

**Comment by Official-Husko** [comment]
> Glad you like it!

I tried the mentioned temporary fix and after putting it to 0 the image still has "artifacts" in it. Due to GitHubs image compression the effect is once again reduced but its definitely noticeable.

2.61 with the mentioned hotfix set to 0
![ShareX_q9jzOj5UPH](https://github.com/darklinkpower/Stardust/assets/27901510/b73b2254-dcea-4b2c-9151-b61bfc0d0aab)

2.60
![ShareX_BWze9fnAXM](https://github.com/darklinkpower/Stardust/assets/27901510/e3b72261-fa22-4ffa-b017-9b873c876b46)

**Comment by darklinkpower** [comment]
It's from the other layer, which doesn't use that opacity value. If you prefer, you can delete them altogether or set a value directly here:

https://github.com/darklinkpower/Stardust/blob/2b0892d6c6350a6d2b5dcedb90db4b68d9cf4206/source/Views/DetailsViewGameOverview.xaml#L92-L99

**Comment by Official-Husko** [comment]
Thank you that fixed the issue completely. Appreciate the quick responses!
