### ISSUE TITLE
[BUG] Extra Metadata Extension/Addon Videos Tab Not Appearing When SuccessStory Achievements Not Set

### ISSUE THREAD

**Issue by sunsetHue** [darklinkpower/Stardust#45]
### Bug Description

Specific game entries are missing their video tab integration from the Extra Metadata Loader addon. 

It seems to be related to the SuccessStory addon and not having achievements set. Videos confirmed to appear and play normally on Harmony, Helium, Mythic and Nova X themes. 

### To Reproduce

1. Install Extra Metadata Loader and SuccessStory.
2. Download trailer with Extra Metadata Loader.
3. Apply Stardust theme.
4. Missing video if achievements not set.

### Screenshots

Working Video Section
![image](https://github.com/darklinkpower/Stardust/assets/171299814/241868cd-23d5-45fb-98f5-4d30b3fbf46a)

Missing Video Section
![image](https://github.com/darklinkpower/Stardust/assets/171299814/6f452436-0f20-451d-8df5-b57e9c0c4353)

Harmony Theme
![image](https://github.com/darklinkpower/Stardust/assets/171299814/4be3ef8e-78a5-4308-b514-723f14035672)

Helium Theme
![image](https://github.com/darklinkpower/Stardust/assets/171299814/752d7702-d180-422a-bace-99e02031de9c)

Mythic Theme
![image](https://github.com/darklinkpower/Stardust/assets/171299814/df79825d-fc21-47e4-9a86-28158b1c3077)

Nova X Theme
![image](https://github.com/darklinkpower/Stardust/assets/171299814/3de4f5ee-4b27-42ff-98d8-d966dc6deaba)

**Comment by darklinkpower** [comment]
Fixed done via https://github.com/darklinkpower/Stardust/commit/10bf4df679f35509c9a2a833fcc0181342b8340e and available in new update.
