### ISSUE TITLE
Issues with new layout in v2.67

### ISSUE THREAD

**Issue by profucius** [darklinkpower/Stardust#48]
### Feature Description

Your v2.67 update changelog stated that you hoped it is well received, or at least few complaints, well unfortunately I must be one of the complaints.

I loved the UI layout of v2.66, it was clean, detailed, and effective. However after updating to v2.67 I not only believe it looks worse from a design standpoint, but it reduces functionality on my screen layout.

I've attached screenshots below showing the differences. In the old one, you can see that the box art doesn't take up unnecessary space, the buttons such as play, edit, HLTB, play history, etc are all on their own line, and that the description pane is 2/3 wide whereas the details pane is 1/3 size, as it should be.

However in the new layout, the box art unnecessarily takes up space, which pushes the details pane further down. Also having everything in only two panes forces it to split 50/50, which reduces the amount of visibility in the description (right) pane, which makes it uglier and harder to read. Also you can see that on the buttons line, the play history gets wrapped to below the play button, which looks ugly.

I propose some changes to this layout if you will.
* Move the play buttons line up to its own line again, as it was on v2.66.
* Remove the dead space above the play buttons and below the features icons (as you'll see in the screenshot, that dead space is a perfect location for the buttons line)
* I would rather the box art be up top again, but if you want to keep that design then at least consider the following:
* Move the Video/Steam screenshots over to the right side in a section of their own (like it is in the new layout) but above the description tabs. Then resize the two panes to be 1/3 and 2/3 sizes like before. This way the description and screenshots can use more space as they deserve, whereas the box art and details pane require less size.

I do want to mention that I appreciate that you're trying new things and want to keep the theme alive. But for now I am going to revert to the v2.66 theme. It is frustrating to have to keep mental track of this and to avoid using "Update All" in my Playnite updates pane. Anyway I hope you'll understand the points I've laid out in this post, and I'm open to discussion, either here or in the discord.

### Screenshots

# v2.66 (old)
![old](https://github.com/user-attachments/assets/3470418b-2cf3-4fbb-b6f0-934fb5955d86)

# v2.67 (new)
![new](https://github.com/user-attachments/assets/245e5570-fa9b-4937-9da4-368d91b19b84)

**Comment by yoshinatsu** [comment]
I agree with the proposals. So much wasted screen real estate.
But for me I'd say the worst offender is the centered game title. Completely ruined the identity of the theme. I would have used a different one if I wanted that style.

I had to revert to 2.66 as well, thankfully I haven't encountered any bugs from the downgrade.
Please remember that we've had YEARS to make our libraries look the way we wanted by tweaking Stardust, even small changes can alter the experience, let alone such drastic changes.

**Comment by profucius** [comment]
My proposal to darklinkpower is that he create a child theme of the major update, so that if he wishes to carry on with the new design, that those of us who wish to remain on the previous version can do so without needing to avoid updating accidentally. 

I prevented my theme from updating by editing the theme.yaml file and changing the version line to be `99.00` which does prevent play ite from detecting the newest update. However going the child theme route would keep it clean in the themes repo, and give more people a chance to have a choice rather than being forced into the developers vision. 

Again I want to reiterate my appreciation of DLP for the theme and his hard work. But I agree with yoshi above that some of us have years (since 2016 for me, so 8 years) fine tuning exactly how we like our UI to appear; We should be allowed to keep it this way if we wish.

**Comment by miros3240** [comment]
I also appreciate the creator's help but I really don't like this update

There are enough designs for other themes, but it's too bad to change the stardust

I think the advantage of stardust is that it is a design that stands out at a glance, so please consider it

**Comment by profucius** [comment]
Thank you for acknowledging us and providing a solution. A bit of a bummer that we won't be in the main release channel anymore. If Playnite ever breaks the theme fork (I can't imagine why, but anything is possible), I hope that you'll consider updating it to keep it functional.

**Comment by yoshinatsu** [comment]
Definitely the best course of action!
Thank you for the new branch DLP!
