### ISSUE TITLE
Playtime vanished in Grid View after upgrade to 2.67

### ISSUE THREAD

**Issue by HexagonIsTheBestagon** [darklinkpower/Stardust#49]
As the title says. It's been a while, so I'm not sure if there is an option somewhere where I can toggle it to show up again. 
Or has it been removed entirely? For now, I have downgraded back to version 2.66.

**Comment by darklinkpower** [comment]
There wasn't any change regarding that in the new version. Do you have it enabled in settings?

![image](https://github.com/user-attachments/assets/312a719b-1f90-41bd-939c-085ce04dfd5c)

**Comment by HexagonIsTheBestagon** [comment]
Yes, but that's Details View, not Grid View. 

![image](https://github.com/user-attachments/assets/62d80bfb-140f-4b9e-b7fa-42b4ba1d0be2)

They've vanished, but in v2.66 they're still there.

**Comment by darklinkpower** [comment]
My screenshot Grid View but I see the issue. You didn't clarify that it was in the game covers specifically so I thought you meant the playtime in the Details Panel in the view. For this version I disabled displaying them in covers by default, but this and more theme options can be enabled by using the ThemeModifier extension: https://playnite.link/addons.html#playnite-thememodifier-plugin

![image](https://github.com/user-attachments/assets/9fc1d854-cb22-43d4-8f33-abbf17e91001)

**Comment by HexagonIsTheBestagon** [comment]
Your screenshot says details view right there, though. I'm not sure what you mean. Anyway, thanks for the tip with Theme Modifier. I'll give the new version another shot after all the kinks are worked out.

**Comment by darklinkpower** [comment]
As an additional tip if you don't want to use ThemeModifier for any reason, you can manually change the option to `Visible` here in your local theme installation but yeah, the extension is the preferred way to go. It has allowed me to expose theme options to users to configure the theme to their liking.
