### ISSUE TITLE
SuccessStory font is now black after update to new UI design

### ISSUE THREAD

**Issue by xauram** [darklinkpower/Stardust#50]
### Bug Description

on updating to the new UI design, the SuccessStory appearance in the details before the description appears to be black in font and I am unsure of what could be causing this issue. It only happens with these past two updates, on this specific theme. Are there any workarounds I can tweak to fix this?

### To Reproduce

N/A

### Extensions log

N/A, crashes do not occur regarding this issue.

### Screenshots

![image](https://github.com/user-attachments/assets/ec55e86a-ea90-4c27-bbfc-faf095616a71)
![image](https://github.com/user-attachments/assets/0a2b6c64-63ce-4ccc-ac4d-eb0135bd7a13)

**Comment by darklinkpower** [comment]
Fixed in new update.

**Comment by xauram** [comment]
I hope your bedroom pillow is the perfect temperature tonight.
