### ISSUE TITLE
Option to don't reserve logo space when not displayed

### ISSUE THREAD

**Issue by Bolthier** [darklinkpower/Stardust#52]
### Feature Description

When using both the extensions Extra Metadata Loader and ThemeModifier the option in Theme Modifier to hide the game name is correctly hiding the game name. When switching to another game with no logo the game name is shown, but is adding additional space below where the logo would be.

It would be nice to have the game name use the space normally reserved for the logo.

Additionally it would be nice for the font size of the game name to be increased if a logo is missing. If possible through the Theme Modifier or automaticly scaled to the reserved space of the logo.

Overall there seems to be a lot of free space between the game name/logo and the details. Its possible to increase the vertical space between the header and the game name/logo through the main settings. Would be nice to either decrease the space for more details to show up or an option through Theme Modifier.

### Screenshots

![Screenshot 2024-09-28 125923](https://github.com/user-attachments/assets/46372f08-1f99-4eb9-bcbb-1117225c392c)
![Screenshot 2024-09-28 130004](https://github.com/user-attachments/assets/0e60780e-39c2-4d41-b221-f50aa6ec0887)

**Comment by darklinkpower** [comment]
This is by design. The reason is to keep the place of the elements consistent also in cases when the logo is missing.

**Comment by Bolthier** [comment]
For the scenario where the game name is only shown when the logo is missing it created the inconsistent appearance, but it's understandable.

**Comment by darklinkpower** [comment]
That's true, it will change slightly if you have the option to not show the game name if the logo is displayed. This is something that I decided after a lot of experimenting, the change was really weird when switching between games with/without logo but if it you think it would be good, I can consider adding an option to not show this spacing.

On a separate topic, is there something you want to add @pcgamehunter or why the thums down?

**Comment by Bolthier** [comment]
If it's not too much work on your side, I'ld really appreciate the option.

Whats your opinion on having an option to increase the font size for the game name?

**Comment by darklinkpower** [comment]
> If it's not too much work on your side, I'ld really appreciate the option.
> 
> Whats your opinion on having an option to increase the font size for the game name?

The game name uses the Largest configured font: https://github.com/darklinkpower/Stardust/blob/fbe3421dfcb235bbca031b4b462c66ce1891cff5/source/Views/DetailsViewGameOverview.xaml#L211

![image](https://github.com/user-attachments/assets/2a46e029-1008-4b5e-a7f5-6ac0180ed735)

Does changing the size here not work for you? If I recall correctly this font size is not used anywhere else so it shouldn't be an issue. If it's still not enough, please open a new issue with the option request.

**Comment by Bolthier** [comment]
@darklinkpower Thanks for the info. That helped.

**Comment by darklinkpower** [comment]
Done in https://github.com/darklinkpower/Stardust/commit/ebfc927c53be030f1aff861b61df59af8b78b2a3

![image](https://github.com/user-attachments/assets/e47f7e03-17dd-45f4-aca5-038027e309a4)
