### ISSUE TITLE
Select options at the bottom of some boxes being cut off

### ISSUE THREAD

**Issue by fernandoepm1** [darklinkpower/Stardust#53]
### Bug Description

Confirm and cancel buttons are being cut off in some features and you are not able to resize the window to have a complete view of the options, you can still select them based on the order, usually the first is the "Confirm" and the second is "Cancel", but you can't really be sure.
This is happening in the Legacy Layout and also the new one

### To Reproduce

I encountered this by using the HowLongToBeat extension and also LibraryManagement extension
Clicking the HowLongToBeat button in the Game detail view opens the selection window for the game, in this window the bottom actions are being cut off, this also happens when adding New Genre/Feature in the Library Management settings.

### Screenshots

HowLongToBeat selection window
![image](https://github.com/user-attachments/assets/b45ccb72-571e-4efd-8b3a-fb3cc370649c)

LibraryManagement settings
![image](https://github.com/user-attachments/assets/dca4e863-8164-4921-bc30-6d7793b96be2)

**Comment by darklinkpower** [comment]
Those layout issues are something that need to be fixed in the extension side. I recommend reporting it to their developer.

**Comment by fernandoepm1** [comment]
Oh, I see, but I tested the same scenarios in 2 other themes and this issue did not occur, in this case shouldn't it happen in all themes? Just curious

**Comment by darklinkpower** [comment]
Basically the extensions window layout is made with specific sizes and dimensions in mind. When any theme changes dimensions, like the Title Bar in this case, it will break. When designing the UI it should be done in a way that is flexible to these type of changes.

**Comment by darklinkpower** [comment]
Although ideally the whole layout should be improve to prevent this, fixing it could be as easy as setting the window `SizeToContent` property. Please let Lacro59 know about this when opening the issues.
