### ISSUE TITLE
About changing the title location in the grid view

### ISSUE THREAD

**Issue by miros3240** [darklinkpower/Stardust#54]
### Feature Description

Hello, I'm using the new stardust theme well and I'm asking because I have a small question while using it.

![1](https://github.com/user-attachments/assets/489a01c8-8bd3-4aa7-96f1-4bb0fa5e36f7)
![2](https://github.com/user-attachments/assets/190ab2e7-1346-4a84-be68-c24d6d7e5bcc)

1. Logos, titles, and library icons appear one after another, taking up a lot of space.
2. The logo and title are shown in order as shown in photo 1, so the same sentence seems to be seen in succession. Of course, even without the logo as shown in photo 2, it looks neat, but I usually used the logo as the standard.

![3](https://github.com/user-attachments/assets/185efa7c-6f5a-4c89-874d-7b6c495adb65)
![4](https://github.com/user-attachments/assets/a5f2e753-8718-45fa-a664-cfeb12b064be)

If you don't mind, ask about moving the title and library icon to the bottom box as shown in photo 3 or raising the bottom a little bit as shown in photo 4

If it's annoying or you don't like it, it's okay. It's a trivial matter, and I'm using it well.

Thank you.

**Comment by darklinkpower** [comment]
Closing under the [recommendation of custom modification.](https://github.com/darklinkpower/Stardust?tab=readme-ov-file#a-note-on-feature-requests)
